trigger:
  branches:
    include:
      - master
      - main

pool:
  name: Azure Pipelines

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    terraform init
    terraform validate
  displayName: 'Terraform Init and Validate'

- script: |
    terraform plan -out main.tfplan 
  displayName: 'Terraform Plan'

- script: |
    terraform apply -input=false main.tfplan
  displayName: 'Terraform Apply'
  env:
    ARM_CLIENT_ID: $(servicePrincipalId)
    ARM_CLIENT_SECRET: $(servicePrincipalKey)
    ARM_SUBSCRIPTION_ID: $(subscriptionId)
    ARM_TENANT_ID: $(tenantId)
