trigger:
  branches:
    include:
      - master
      - main

pool:
  name: Azure Pipelines

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: az login --service-principal -u (servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
  displayName: 'Azure Login'
  env:
    ARM_CLIENT_ID: $(servicePrincipalId)
    ARM_CLIENT_SECRET: $(servicePrincipalKey)
    ARM_TENANT_ID: $(tenantId)
    ARM_SUBSCRIPTION_ID: $(subscriptionId)

- script: terraform init
  displayName: 'Terraform Init'

- script: terraform validate
  displayName: 'Terraform Validate'

- script: terraform plan -out main.tfplan
  displayName: 'Terraform Plan'

- script: terraform apply -input=false main.tfplan
  displayName: 'Terraform Apply'
  condition: succeeded()
